const sandboxDir = '/home/ask/ubuntu-scripts-tester/sandbox';

const setupCommands = {
  '1_find_system_groups.sh': `mkdir -p ${sandboxDir} && touch ${sandboxDir}/test_passwd && echo "Настройка песочницы для тестирования 1_find_system_groups.sh завершена"`,
  '2_find_files_with_access_rights.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/file2 && chmod u+x,g+w ${sandboxDir}/test_dir/file1 && chmod u+x,g-w ${sandboxDir}/test_dir/file2 && echo "Настройка песочницы для тестирования 2_find_files_with_access_rights.sh завершена"`,
  '3_find_all_scripts.sh': `mkdir -p ${sandboxDir}/test_dir && echo '#!/bin/bash' > ${sandboxDir}/test_dir/script1.sh && chmod +x ${sandboxDir}/test_dir/script1.sh && echo 'echo "Hello, World!"' >> ${sandboxDir}/test_dir/script1.sh && echo "Настройка песочницы для тестирования 3_find_all_scripts.sh завершена"`,
  '4_search_scripts_by_user.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/script1.sh && chmod +x ${sandboxDir}/test_dir/script1.sh && echo "Настройка песочницы для тестирования 4_search_scripts_by_user.sh завершена"`,
  '5_recursive_search_words.sh': `mkdir -p ${sandboxDir}/test_dir && echo "This is a test file" > ${sandboxDir}/test_dir/test.txt && echo "Настройка песочницы для тестирования 5_recursive_search_words.sh завершена"`,
  '6_find_duplicate_files.sh': `mkdir -p ${sandboxDir}/test_dir && echo "Test file content" > ${sandboxDir}/test_dir/file1.txt && echo "Test file content" > ${sandboxDir}/test_dir/file2.txt && echo "Настройка песочницы для тестирования 6_find_duplicate_files.sh завершена"`,
  '7_find_symbolic_links.sh': `mkdir -p ${sandboxDir}/test_dir && ln -s ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 7_find_symbolic_links.sh завершена"`,
  '8_find_hard_links.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/hardlink1 && echo "Настройка песочницы для тестирования 8_find_hard_links.sh завершена"`,
  '9_find_names_by_inode.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && echo "Настройка песочницы для тестирования 9_find_names_by_inode.sh завершена"`,
  '10_find_names_by_inode_multiple_partitions.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && echo "Настройка песочницы для тестирования 10_find_names_by_inode_multiple_partitions.sh завершена"`,
  '11_delete_file_with_links.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln -s ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 11_delete_file_with_links.sh завершена"`,
  '12_recursive_change_permissions.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && chmod 644 ${sandboxDir}/test_dir/file1 && echo "Настройка песочницы для тестирования 12_recursive_change_permissions.sh завершена"`,
  '13_compare_directories.sh': `mkdir -p ${sandboxDir}/dir1 && mkdir -p ${sandboxDir}/dir2 && echo "File in dir1" > ${sandboxDir}/dir1/file1.txt && echo "File in dir2" > ${sandboxDir}/dir2/file1.txt && echo "Настройка песочницы для тестирования 13_compare_directories.sh завершена"`,
  // Добавьте команды для настройки окружения здесь
  '14_get_mac_addresses.sh': `echo "Настройка песочницы не требуется для тестирования 14_get_mac_addresses.sh"`,
  '15_list_authorized_users.sh': `echo "Настройка песочницы не требуется для тестирования 15_list_authorized_users.sh"`,
  '16_list_active_network_connections.sh': `echo "Настройка песочницы не требуется для тестирования 16_list_active_network_connections.sh"`,
  '17_reassign_symbolic_link.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln -s ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 17_reassign_symbolic_link.sh завершена"`,
  '18_create_symbolic_links.sh': `mkdir -p ${sandboxDir}/test_dir && echo "/path/to/file1" > ${sandboxDir}/file_list && echo "Настройка песочницы для тестирования 18_create_symbolic_links.sh завершена"`,
  '19_copy_directory_with_links.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln -s ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 19_copy_directory_with_links.sh завершена"`,
  '20_copy_directory_with_symlinks.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln -s ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 20_copy_directory_with_symlinks.sh завершена"`,
  '21_copy_with_attributes.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && echo "Настройка песочницы для тестирования 21_copy_with_attributes.sh завершена"`,
  '22_convert_relative_to_direct_links.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln -s file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 22_convert_relative_to_direct_links.sh завершена"`,
  '23_convert_direct_to_relative_links.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && ln -s ${sandboxDir}/test_dir/file1 ${sandboxDir}/test_dir/link1 && echo "Настройка песочницы для тестирования 23_convert_direct_to_relative_links.sh завершена"`,
  '24_find_and_delete_broken_links.sh': `mkdir -p ${sandboxDir}/test_dir && ln -s ${sandboxDir}/test_dir/non_existent ${sandboxDir}/test_dir/broken_link && echo "Настройка песочницы для тестирования 24_find_and_delete_broken_links.sh завершена"`,
  '25_unpack_archive.sh': `mkdir -p ${sandboxDir}/test_dir && echo "Test file" > ${sandboxDir}/test_dir/file1 && tar -cvf ${sandboxDir}/test_archive.tar ${sandboxDir}/test_dir && echo "Настройка песочницы для тестирования 25_unpack_archive.sh завершена"`,
  '26_pack_directory_with_attributes.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1 && echo "Настройка песочницы для тестирования 26_pack_directory_with_attributes.sh завершена"`,
  '27_copy_directory_structure.sh': `mkdir -p ${sandboxDir}/test_dir/subdir1 && mkdir -p ${sandboxDir}/test_dir/subdir2 && echo "Настройка песочницы для тестирования 27_copy_directory_structure.sh завершена"`,
  '28_list_users_alphabetically.sh': `echo "Настройка песочницы не требуется для тестирования 28_list_users_alphabetically.sh"`,
  '29_list_system_users_sorted_by_id.sh': `echo "Настройка песочницы не требуется для тестирования 29_list_system_users_sorted_by_id.sh"`,
  '30_list_users_sorted_by_reverse_id.sh': `echo "Настройка песочницы не требуется для тестирования 30_list_users_sorted_by_reverse_id.sh"`,
  '31_list_users_without_authorization_rights.sh': `echo "Настройка песочницы не требуется для тестирования 31_list_users_without_authorization_rights.sh"`,
  '32_list_users_with_or_without_terminal.sh': `echo "Настройка песочницы не требуется для тестирования 32_list_users_with_or_without_terminal.sh"`,
  '33_download_all_links_from_page.sh': `echo "Настройка песочницы не требуется для тестирования 33_download_all_links_from_page.sh"`,
  '34_stop_long_running_processes.sh': `echo "Настройка песочницы не требуется для тестирования 34_stop_long_running_processes.sh"`,
  '35_delete_orphaned_jpeg_files.sh': `mkdir -p ${sandboxDir}/test_dir && touch ${sandboxDir}/test_dir/file1.txt && touch ${sandboxDir}/test_dir/file1.jpeg && touch ${sandboxDir}/test_dir/file2.jpeg && echo "Настройка песочницы для тестирования 35_delete_orphaned_jpeg_files.sh завершена"`,
  '36_find_ip_address.sh': `echo "Настройка песочницы не требуется для тестирования 36_find_ip_address.sh"`,
  '37_get_all_ip_addresses_from_file.sh': `mkdir -p ${sandboxDir}/test_dir && echo "192.168.1.1" > ${sandboxDir}/test_dir/ips.txt && echo "10.0.0.1" >> ${sandboxDir}/test_dir/ips.txt && echo "Настройка песочницы для тестирования 37_get_all_ip_addresses_from_file.sh завершена"`,
  '38_find_active_hosts.sh': `mkdir -p ${sandboxDir}/test_dir && echo "192.168.1.1" > ${sandboxDir}/test_dir/hosts.txt && echo "10.0.0.1" >> ${sandboxDir}/test_dir/hosts.txt && echo "Настройка песочницы для тестирования 38_find_active_hosts.sh завершена"`,
  '39_get_raised_interfaces_ips.sh': `echo "Настройка песочницы не требуется для тестирования 39_get_raised_interfaces_ips.sh"`,
  '40_get_subdomains_from_ssl.sh': `echo "Настройка песочницы не требуется для тестирования 40_get_subdomains_from_ssl.sh"`,
  '41_extract_path_name_extension.sh': `echo "Настройка песочницы не требуется для тестирования 41_extract_path_name_extension.sh"`,
  '42_delete_files_by_size_and_pattern.sh': `mkdir -p ${sandboxDir}/test_dir && dd if=/dev/zero of=${sandboxDir}/test_dir/file1.txt bs=1 count=22 && touch ${sandboxDir}/test_dir/file2.txt && echo "Настройка песочницы для тестирования 42_delete_files_by_size_and_pattern.sh завершена"`,
  '43_create_files_with_identifiers.sh': `mkdir -p ${sandboxDir}/test_dir && echo "${sandboxDir}/test_dir/file1 1234" > ${sandboxDir}/file_list && echo "${sandboxDir}/test_dir/file2 5678" >> ${sandboxDir}/file_list && echo "Настройка песочницы для тестирования 43_create_files_with_identifiers.sh завершена"`,
};

const commands = {
  '1_find_system_groups.sh': `cut -d: -f1,3 /etc/group | grep -E ':[0-9]{1,3}$' > ${sandboxDir}/sys_groups && cat ${sandboxDir}/sys_groups`,
  '2_find_files_with_access_rights.sh': `find . -perm -u=x,g=w`,
  '3_find_all_scripts.sh': `find . -type f -executable -exec sh -c '[ "$(head -c2 "$1")" = "#!" ] && echo "$1"' _ {} \\; && echo "Task completed"`,
  '4_search_scripts_by_user.sh': `sudo -u root -H find . -type f -executable -exec sh -c 'head -c2 "$1" | grep -q "#!" && echo "$1"' _ {} \\; && echo "Task completed"`,
  '5_recursive_search_words.sh': `grep -r --include=*.txt "file" && echo "Task completed"`,
  '6_find_duplicate_files.sh': `find . -type f -exec md5sum {} + | sort | uniq -D -w32 | sort -k2 && echo "Task completed"`,
  '7_find_symbolic_links.sh': `find . -type l -lname *file1.txt && echo "Task completed"`,
  '8_find_hard_links.sh': `find ${sandboxDir}/test_dir -samefile ${sandboxDir}/test_dir/file1 && echo "Task completed"`,
  '9_find_names_by_inode.sh': `ls -i ${sandboxDir}/test_dir/file1 | cut -d' ' -f1 | xargs find ${sandboxDir}/test_dir -inum && echo "Task completed"`,
  '10_find_names_by_inode_multiple_partitions.sh': `ls -i ${sandboxDir}/test_dir/file1 | cut -d' ' -f1 | xargs find ${sandboxDir}/test_dir -xdev -inum && echo "Task completed"`,
  '11_delete_file_with_links.sh': `sudo find -L ${sandboxDir}/test_dir -samefile ${sandboxDir}/test_dir/file1 && echo "Task completed"`,
  '12_recursive_change_permissions.sh': `find ${sandboxDir}/test_dir -type f -perm 644 -exec chmod 640 {} \\; && echo "Task completed"`,
  '13_compare_directories.sh': `diff -rN -u5 ${sandboxDir}/dir1/ ${sandboxDir}/dir2/ && echo "Task completed"`,
  '14_get_mac_addresses.sh': `ip link | grep ether | xargs -n4 | cut -d' ' -f2 && echo "Task completed"`,
  '15_list_authorized_users.sh': `sudo users | xargs -n1 | sort -u && echo "Task completed"`,
  '16_list_active_network_connections.sh': `ss -atOH | cut -d' ' -f1 | sort | xargs -n1 | uniq -c && echo "Task completed"`,
  '17_reassign_symbolic_link.sh': `readlink ${sandboxDir}/test_dir/link1 | xargs -I {} ln -srf {} ${sandboxDir}/test_dir/link1 && echo "Task completed"`,
  '18_create_symbolic_links.sh': `mkdir -p ${sandboxDir}/sym_dir && cat ${sandboxDir}/file_list | xargs -I{} sh -c 'ln -sbrf {} ${sandboxDir}/sym_dir/link_to_$(basename {})' && echo "Task completed"`,
  '19_copy_directory_with_links.sh': `cp -a ${sandboxDir}/test_dir ${sandboxDir}/backup/ && rsync -al ${sandboxDir}/test_dir/ ${sandboxDir}/rsync_backup/ && echo "Task completed"`,
  '20_copy_directory_with_symlinks.sh': `cp -a ${sandboxDir}/test_dir ${sandboxDir}/archive/ && echo "Task completed"`,
  '21_copy_with_attributes.sh': `cp -rp ${sandboxDir}/test_dir ${sandboxDir}/dir4/ && echo "Task completed"`,
  '22_convert_relative_to_direct_links.sh': `find ${sandboxDir}/test_dir -type l | xargs -I{} sh -c 'ln -sf $(realpath {}) {}' && echo "Task completed"`,
  '23_convert_direct_to_relative_links.sh': `find ${sandboxDir}/test_dir -type l | xargs -I{} sh -c 'ln -srf $(readlink {}) {}' && echo "Task completed"`,
  '24_find_and_delete_broken_links.sh': `find ${sandboxDir}/test_dir -xtype l -delete && echo "Task completed"`,
  '25_unpack_archive.sh': `tar -xvf ${sandboxDir}/arc.tar -C ${sandboxDir}/unpacked && echo "Task completed"`,
  '26_pack_directory_with_attributes.sh': `sudo tar -Jcf ${sandboxDir}/arc.tar.xz ${sandboxDir}/dir1/ && sudo tar -xf ${sandboxDir}/arc.tar.xz -C ${sandboxDir} && echo "Task completed"`,
  '27_copy_directory_structure.sh': `find ${sandboxDir}/dir1/ -type d -print | xargs -I{} mkdir -p ${sandboxDir}/dir_structure/{} && echo "Task completed"`,
  '28_list_users_alphabetically.sh': `cut -d: -f1,3 /etc/passwd | grep -E ":[0-9]{4,}$" | cut -d: -f1 | sort && echo "Task completed"`,
  '29_list_system_users_sorted_by_id.sh': `cut -d: -f1,3 /etc/passwd | grep -E ":[0-9]{1,3}$" | sort -t: -nk2 | tr ':' ' ' && echo "Task completed"`,
  '30_list_users_sorted_by_reverse_id.sh': `cut -d: -f1,3 /etc/passwd | grep -E ":[0-9]{1,3}$" | sort -t: -rnk2 | cut -d: -f1 && echo "Task completed"`,
  '31_list_users_without_authorization_rights.sh': `sudo cut -d: -f1,2 /etc/shadow | grep -vE ':\!\*' | cut -d: -f1 && sudo cut -d: -f1,2 /etc/shadow | grep -E ':\!\*' | cut -d: -f1 && echo "Task completed"`,
  '32_list_users_with_or_without_terminal.sh': `cut -d: -f1,7 /etc/passwd | grep -E "/(bash|sh|zsh)$" | cut -d: -f1 && cut -d: -f1,7 /etc/passwd | grep -vE "/(bash|sh|zsh)$" | cut -d: -f1 && echo "Task completed"`,
  '33_download_all_links_from_page.sh': `wget -qO - https://abc.xyz/ | grep -oP 'href="\\K[^"]+' | xargs -I{} wget -P ${sandboxDir}/downloads/ {} && echo "Task completed"`,
  '34_stop_long_running_processes.sh': `ps -eo comm= | xargs -n1 killall -o 5d && find /proc -maxdepth 1 -type d -ctime +5 | grep -oP '/\\K[0-9]+' | xargs kill -9 && echo "Task completed"`,
  '35_delete_orphaned_jpeg_files.sh': `find ${sandboxDir}/test_dir -type f -name '*.jpeg' | xargs -I{} sh -c 'pname="$(dirname {})/$(basename -s .jpeg {})"; [ ! -e \${pname}.txt ] && rm \${pname}.jpeg' && echo "Task completed"`,
  '36_find_ip_address.sh': `ip -o addr | grep inet | cut -d ' ' -f2,7 | tail -n +3 && echo "Task completed"`,
  '37_get_all_ip_addresses_from_file.sh': `grep -oP '\\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\b' ${sandboxDir}/test_dir/ips.txt && sudo grep -P '\\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\b' /etc/netplan/*.yaml | xargs && echo "Task completed"`,
  '38_find_active_hosts.sh': `nmap -sn 192.168.56.0/24 && nmap -sn -iL ${sandboxDir}/test_dir/hosts.txt && printf "192.168.1.%d\\n" {1..254} | xargs -I{} ping -c1 {} > /dev/null; ip -4 n | grep REACHABLE | cut -d ' ' -f1 && cat ${sandboxDir}/test_dir/hosts.txt | xargs -I{} ping -c1 {} > /dev/null; ip -4 n | grep REACHABLE | cut -d ' ' -f1 && echo "Task completed"`,
  '39_get_raised_interfaces_ips.sh': `ip a | grep 'state UP' | cut -d ' ' -f2 | xargs -n1 ip a show | grep inet | cut -d ' ' -f5,6 && sudo grep -P '\\b(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\b' /etc/netplan/*.yaml | xargs && echo "Task completed"`,
  '40_get_subdomains_from_ssl.sh': `echo | openssl s_client -connect microsoft.com:443 2>/dev/null | openssl x509 -noout -ext subjectAltName | tail -n +2 | xargs -n1 | cut -d: -f2 | tr -d ' ' && echo "Task completed"`,
  '41_extract_path_name_extension.sh': `file='./dir1/file1.txt'; path=$(dirname $file); name=$(basename \${file%.*}); ext=\${file##*.}; echo $path $name $ext && echo "Task completed"`,
  '42_delete_files_by_size_and_pattern.sh': `find ${sandboxDir}/test_dir -type f -size 22c -name '*.txt' -delete && echo "Task completed"`,
  '43_create_files_with_identifiers.sh': `xargs -a ${sandboxDir}/hash_file_list -n2 sh -c 'mkdir -p $(dirname $1) && echo $2 > $1' && echo "Task completed"`
};

const destroyCommands = {
  '1_find_system_groups.sh': `rm -rf ${sandboxDir}`,
  '2_find_files_with_access_rights.sh': `rm -rf ${sandboxDir}`,
  '3_find_all_scripts.sh': `rm -rf ${sandboxDir}`,
  '4_search_scripts_by_user.sh': `rm -rf ${sandboxDir}`,
  '5_recursive_search_words.sh': `rm -rf ${sandboxDir}`,
  '6_find_duplicate_files.sh': `rm -rf ${sandboxDir}`,
  '7_find_symbolic_links.sh': `rm -rf ${sandboxDir}`,
  '8_find_hard_links.sh': `rm -rf ${sandboxDir}`,
  '9_find_names_by_inode.sh': `rm -rf ${sandboxDir}`,
  '10_find_names_by_inode_multiple_partitions.sh': `rm -rf ${sandboxDir}`,
  '11_delete_file_with_links.sh': `rm -rf ${sandboxDir}`,
  '12_recursive_change_permissions.sh': `rm -rf ${sandboxDir}`,
  '13_compare_directories.sh': `rm -rf ${sandboxDir}`,
  '14_get_mac_addresses.sh': `echo "Окружение не требовалось"`,
  '15_list_authorized_users.sh': `echo "Окружение не требовалось"`,
  '16_list_active_network_connections.sh': `echo "Окружение не требовалось"`,
  '17_reassign_symbolic_link.sh': `rm -rf ${sandboxDir}`,
  '18_create_symbolic_links.sh': `rm -rf ${sandboxDir}`,
  '19_copy_directory_with_links.sh': `rm -rf ${sandboxDir}`,
  '20_copy_directory_with_symlinks.sh': `rm -rf ${sandboxDir}`,
  '21_copy_with_attributes.sh': `rm -rf ${sandboxDir}`,
  '22_convert_relative_to_direct_links.sh': `rm -rf ${sandboxDir}`,
  '23_convert_direct_to_relative_links.sh': `rm -rf ${sandboxDir}`,
  '24_find_and_delete_broken_links.sh': `rm -rf ${sandboxDir}`,
  '25_unpack_archive.sh': `rm -rf ${sandboxDir}`,
  '26_pack_directory_with_attributes.sh': `rm -rf ${sandboxDir}`,
  '27_copy_directory_structure.sh': `rm -rf ${sandboxDir}`,
  '28_list_users_alphabetically.sh': `echo "Окружение не требовалось"`,
  '29_list_system_users_sorted_by_id.sh': `echo "Окружение не требовалось"`,
  '30_list_users_sorted_by_reverse_id.sh': `echo "Окружение не требовалось"`,
  '31_list_users_without_authorization_rights.sh': `echo "Окружение не требовалось"`,
  '32_list_users_with_or_without_terminal.sh': `echo "Окружение не требовалось"`,
  '33_download_all_links_from_page.sh': `echo "Окружение не требовалось"`,
  '34_stop_long_running_processes.sh': `echo "Окружение не требовалось"`,
  '35_delete_orphaned_jpeg_files.sh': `rm -rf ${sandboxDir}`,
  '36_find_ip_address.sh': `echo "Окружение не требовалось"`,
  '37_get_all_ip_addresses_from_file.sh': `rm -rf ${sandboxDir}`,
  '38_find_active_hosts.sh': `rm -rf ${sandboxDir}`,
  '39_get_raised_interfaces_ips.sh': `echo "Окружение не требовалось"`,
  '40_get_subdomains_from_ssl.sh': `echo "Окружение не требовалось"`,
  '41_extract_path_name_extension.sh': `echo "Окружение не требовалось"`,
  '42_delete_files_by_size_and_pattern.sh': `rm -rf ${sandboxDir}`,
  '43_create_files_with_identifiers.sh': `rm -rf ${sandboxDir}`,
};

module.exports = { setupCommands, commands, destroyCommands, sandboxDir };
